export enum AuthorResponseCodes {
    AUTHOR_CREATED = 'ATOR-C00',
    AUTHOR_UPDATED = 'ATOR-U00',
    ALREADY_EXISTS = 'ATOR-E02',
    SUCCESS_GETALL = 'ATOR-S00',
    SUCCESS_GET_AUTHR = 'ATOR-S00',
    ERROR_PATH = 'ATOR-400',
    AUTHOR_NOT_EXIST = 'ATOR-E04',
    SUCCESS_DELTED_AUTHR = 'ATOR-D02',
}
