export enum AuthResponseCodes {
    NO_TOKEN = 'AUTH-E00',
    MISSING_FIELDS = 'AUTH-E01',
    ALREADY_EXISTS = 'AUTH-E02',
    WRONG_EMAIL_OR_PASSWORD = 'AUTH-E03',
    INVALID_TOKEN = 'AUTH-E05',
    SUCCESS_SIGNUP = 'AUTH-S00',
    SUCCESS_LOGIN = 'AUTH-S01',
    PASSWORD_SUCESSFULLY_UPDATED = 'AUTH-S02',
}
