export enum PublicationResponseCodes {
    PUBLICATION_CREATED = 'PUBL-C00',
    PUBLICATION_UPDATED = 'PUBL-U00',
    ALREADY_EXISTS = 'PUBL-E02',
    SUCCESS_GETALL = 'PUBL-S00',
    SUCCESS_GET_PUBL = 'PUBL-S00',
    ERROR_PATH = 'PUBL-400',
    PUBLICATION_NOT_EXIST = 'PUBL-E04',
    SUCCESS_DELTED_PUBL = 'PUBL-D02',
}
